### PR TITLE
Add coord_system kwarg to get/apply_sun_pitch_yaw and change default sign

### LINKED ISSUE #30: Allow specifying get_sun_pitch_yaw coordinate convention and change default
The current definition of yaw about the sun line matches ORviewer, but this does not match the engineering convention where +yaw is in the same sense as spacecraft body yaw.

The new default should match the engineering sense, go from 0 to 360, and have zero be defined as the ECI z-axis if the Sun is at exactly RA = Dec = 0.

Add a keyword argument `coord_system` which can take the values `"spacecraft"` or `"ORviewer"`.

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

The current definition of yaw about the sun line matches ORviewer, but this does not match the engineering convention where +yaw is in the same sense as spacecraft body yaw.

The new default matches the engineering sense: it goes from 0 to 360, and has zero be defined as the ECI z-axis if the Sun is at exactly RA = Dec = 0.

This PR adds a keyword argument coord_system which can take the values "spacecraft" or "ORviewer", where "spacecraft" is the default.

Fixes #30

## Interface impacts

Changes the sense of the `yaw` parameter. Tests for sparkles need update (https://github.com/sot/sparkles/pull/206).

### Unit tests

- [x] Mac (new unit tests)
```
(ska3) ➜  ska_sun git:(add-spacecraft-system) git rev-parse HEAD             
3579ca1593a3fafb12d7cd67bec4c1de7cdbba42
(ska3) ➜  ska_sun git:(add-spacecraft-system) pytest
====================================================== test session starts ======================================================
platform darwin -- Python 3.10.8, pytest-7.2.1, pluggy-1.0.0
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: timeout-2.1.0, anyio-3.6.2
collected 19 items                                                                                                              

ska_sun/tests/test_sun.py ...................                                                                             [100%]

====================================================== 19 passed in 4.62s =======================================================
```

Independent check of unit tests by Jean
- [x] Linux

```
(ska3-flight-2024.0rc7) jeanconn-fido> pytest
============================================================= test session starts ==============================================================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
rootdir: /proj/sot/ska/jeanproj/git
configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.2.0
collected 19 items                                                                                                                             

ska_sun/tests/test_sun.py ...................                                                                                            [100%]

=============================================================== warnings summary ===============================================================
../../../../../../fido.real/conda/envs/ska3-flight-2024.0rc7/lib/python3.11/site-packages/ska_helpers/version.py:25
  /fido.real/conda/envs/ska3-flight-2024.0rc7/lib/python3.11/site-packages/ska_helpers/version.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import DistributionNotFound, get_distribution

../../../../../../fido.real/conda/envs/ska3-flight-2024.0rc7/lib/python3.11/site-packages/pkg_resources/__init__.py:2868
  /fido.real/conda/envs/ska3-flight-2024.0rc7/lib/python3.11/site-packages/pkg_resources/__init__.py:2868: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= 19 passed, 2 warnings in 32.61s ========================================================
(ska3-flight-2024.0rc7) jeanconn-fido> git rev-parse HEAD
3579ca1593a3fafb12d7cd67bec4c1de7cdbba42
```

### Functional tests

Plotted the `yaw` value around the 2024:036 NSM yaw bias maneuver using https://gist.github.com/taldcroft/1caaaa0fcddd15e56a51126c869d04e3:

image

### CODE REVIEW

**Comment by jeanconn** [comment]
We still don't have much data to line up.  With regard to a "positive yaw bias of 0.025 deg/s for 30 minutes", I thought maybe a positive bias would move us in the negative yaw direction.  But I guess the sign convention could be the "bias that makes it go positive" is positive?

**Comment by taldcroft** [comment]
I think the language is now unambiguous and clear. There is no ambiguity in what a "positive" number is, and so the "positive yaw bias" refers to the value of +0.025 deg/s that is used as input when creating command loads from an RTS.

I specifically added this text to both of the docstrings to remind our future selves.

**Comment by taldcroft** [comment]
> We still don't have much data to line up.

I'm not sure what that means, but with regards to confirming a sign convention you only need one case.

**Comment by jeanconn** [comment]
Regarding "with regards to confirming a sign convention you only need one case." sure, I just hadn't been looped in on this case.  It sounds like you have the convention from the RTS which is fine.  I also wasn't sure what you plotted for `yaw` to confirm it matches expectations -- I assume that is just derived using the code here.

**Comment by jeanconn** [comment]
We'll need an update to sparkles test_find_er_catalog to go with this.

**Comment by taldcroft** [comment]
I added a link to the [notebook I used to make the plot](https://gist.github.com/taldcroft/1caaaa0fcddd15e56a51126c869d04e3) in the description and here.

**Comment by taldcroft** [comment]
For reference, the yaw bias RTS is named A_TIMED_YAWBIAS.RTS. This appears in Slack in #anomaly_response_recovery along with "positive yaw bias of 0.025 deg for 30 mins".

**Review by jeanconn — APPROVED** [review]

**Pull request merged**
