### PR TITLE
Change allowed_rolldev to use chandra_models

### LINKED ISSUE #26: Remove pitch roll constraint package data and use chandra_models
The data file for this should come from `chandra_models` (https://github.com/sot/chandra_models/issues/102).

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

Use the pitch-roll constraint CSV data file in `chandra_models` via the interface in `ska_helpers.chandra_models` to import the table of pitch vs. off-nominal roll data.

### Requires
- [ ] https://github.com/sot/chandra_models/pull/104
- [ ] https://github.com/sot/ska_helpers/pull/32

Fixes #26

## Interface impacts

No API changes, but smaller available available pitch/roll space available.

### Unit tests

- [x] Mac

Independent check of unit tests by Jean
- [x] Linux ska3-prime 2023.1rc9

### Functional tests

No functional testing.

### CODE REVIEW

**Comment by jeanconn** [comment]
I put the updated ska_helpers in PYTHONPATH, updated my $SKA/data/chandra_models to the pitch-roll-constraint branch, and ran tests here and get failed tests that chandra_models isn't at 3.47.
```
FAILED ska_sun/tests/test_sun.py::test_allowed_rolldev[0.0--1.0] - ValueError: repo tip is not at tag 3.47
```
This is on linux.  Not sure what I'm missing just yet.

**Comment by jeanconn** [comment]
Nope.  That was me just accidentally running the ska_sun test from chandra_models after I went to double check it was at the right version.  Deleting this comment and the last.

**Comment by jskrist** [comment]
@jeanconn, I also bumped on the `repo tip is not at tag` thing.  I think the intention is to make sure that the user is getting the data they expect (typically the latest data), but I wonder if there is a way to check if the data file to be read has any modifications, as local modifications would also cause potentially unexpected data to be returned.

perhaps this should be a log message or warning instead of an exception, or have some way for a power user/dev to skip this check/exception when working in a development environment?

**Comment by jeanconn** [comment]
@jskrist it looks like it will stop complaining if I add a tag in the testing commit in chandra_models, which is probably a fine work around for the power-testing user.

**Review by jeanconn — APPROVED** [review]

**Pull request merged**
